server:
  children:
    application:
      hosts:
        lfinal-app:
          ansible_host: 158.160.27.11
          ansible_user: user
          ansible_ssh_private_key_file: /home/xman/.ssh/id_rsa_rebrain
    database:
      hosts:
        lfinal-db:
         ansible_host: 158.160.1.91
         ansible_user: user
         ansible_ssh_private_key_file: /home/xman/.ssh/id_rsa_rebrain
    monitoring:
      hosts:
        lfinal-mon:
          ansible_host: 89.169.163.209
          ansible_user: user
          ansible_ssh_private_key_file: /home/xman/.ssh/id_rsa_rebrain
    storage:
      hosts:
        lfinal-nfs:
          ansible_host: 158.160.15.60
          ansible_user: user
          ansible_ssh_private_key_file: /home/xman/.ssh/id_rsa_rebrain