server:
  children:
    application:
      hosts:
        lfinal-app:
          ansible_host: 158.160.27.11
    database:
      hosts:
        lfinal-db:
          ansible_host: 158.160.1.91
    monitoring:
      hosts:
        lfinal-mon:
          ansible_host: 89.169.163.209
    storage:
      hosts:
        lfinal-nfs:
          ansible_host: 158.160.15.60