- hosts: new
  become: true
  tasks:
   
    - import_tasks: ./tasks/apt_proxy_settings.yml      
    - import_tasks: ./tasks/apt_update_upgrage_autoremove.yml 
    - import_tasks: ./tasks/zabbix_agent_install.yml
    - import_tasks: ./tasks/ntp_settings.yml

    - name: Set locale to RU
      ansible.builtin.shell: localectl set-locale LANG=ru_RU.UTF-8
      
    - name: Set a hostname
      ansible.builtin.hostname: name={{ inventory_hostname }}

    - name: Edit /etc/hosts
      block:
      - name: Replace a localhost entry 
        ansible.builtin.lineinfile:
          path: /etc/hosts
          search_string: '127.0.1.1'
          line: 127.0.1.1 {{ inventory_hostname }}
      - name: Edit hosts file
        ansible.builtin.lineinfile:
          path: /etc/hosts
          line: "{{ ansible_host }} {{ inventory_hostname }}"
          create: yes

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: 
        path: /var/run/reboot-required
        get_checksum: true 
        checksum_algorithm: md5

    - name: Reboot if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
