---
- hosts: video
  become: true
  become_user: root
  tasks:

    - shell: rm -rf /etc/zabbix/zabbix_agent2.d/*.conf
    - shell: rm -rf /etc/zabbix/zabbix_agent2.d/*.sh

    - import_tasks: ./tasks/zabbix_add_user_parameters.yml