- name: Add NTP server
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    search_string: '#NTP='
    line: NTP=172.16.4.254

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: Reload service timesync
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    state: restarted
    daemon_reload: true