- name: Install a .deb package from the internet
  block:
  - name: 20.04
    ansible.builtin.apt:
      deb: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu20.04_all.deb
      state: present
    when: ansible_distribution_version == "20.04"
  - name: 22.04
    ansible.builtin.apt:
      deb: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu22.04_all.deb
      state: present
    when: ansible_distribution_version == "22.04"
  - name: 24.04
    ansible.builtin.apt:
      deb: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu24.04_all.deb
      state: present
    when: ansible_distribution_version == "24.04"