- name: Install a .deb package from the internet
  block:
  - name: 20.04
    ansible.builtin.apt:
      deb: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu20.04_all.deb
      state: present
    when: ansible_distribution_version == "20.04"
  - name: 22.04
    ansible.builtin.apt:
      deb: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu22.04_all.deb
      state: present
    when: ansible_distribution_version == "22.04"
  - name: 24.04
    ansible.builtin.apt:
      deb: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest%2Bubuntu24.04_all.deb
      state: present
    when: ansible_distribution_version == "24.04"

- name: Install zabbix
  ansible.builtin.apt:
    name: 
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present
    update_cache: true

- name: Edit /etc/zabbix/zabbix_agent2.conf
  block:
  - name: Set Server
    ansible.builtin.lineinfile:
      path:  /etc/zabbix/zabbix_agent2.conf
      search_string: 'Server='
      line: Server=172.16.5.202
  - name: Set ServerActive
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      search_string: 'ServerActive='
      line: ServerActive=172.16.5.202

- name: Delete nvidia plugin
  ansible.builtin.file:
    path: /etc/zabbix/zabbix_agent2.d/plugins.d/nvidia.conf
    state: absent

- name: Reload Zabbix agent
  ansible.builtin.systemd_service:
    name: zabbix-agent2.service
    state: restarted
    daemon_reload: true
