# - name: Edit /etc/hosts
#   block:
#   - name: Replace a localhost entry 
#     ansible.builtin.lineinfile:
#       path: /etc/hosts
#       search_string: '127.0.1.1'
#       line: 127.0.1.1 {{ inventory_hostname }}
#   - name: Edit hosts file
#     ansible.builtin.lineinfile:
#       path: /etc/hosts
#       line: "{{ ansible_host }} {{ inventory_hostname }}"
#       create: yes



# - name: Edit /etc/hosts
#   ansible.builtin.blockinfile:
#     path: /etc/hosts
#     create: true
#     block: |
#       "{{ ansible_host }} {{ inventory_hostname }}"


# "{{ ansible_host }} {{ inventory_hostname }}"

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"