- name: Install NFS
  ansible.builtin.apt:
    name: 
      - nfs-kernel-server 
      - nfs-common
    state: present
    update_cache: true

- name: Create a ext4 filesystem on b
  community.general.filesystem:
    fstype: ext4
    dev: /dev/vdb

- name: Create a ext4 filesystem on c
  community.general.filesystem:
    fstype: ext4
    dev: /dev/vdc

- name: Create a ext4 filesystem on d
  community.general.filesystem:
    fstype: ext4
    dev: /dev/vdd


- name: Create a directory
  ansible.builtin.file:
    path: /mnt/nextcloud
    state: directory
    mode: '0755'

- name: Create a directory
  ansible.builtin.file:
    path: /mnt/logs
    state: directory
    mode: '0755'

- name: Create a directory
  ansible.builtin.file:
    path: /mnt/prometheus
    state: directory
    mode: '0755'


- name: Mount 
  ansible.posix.mount:
    path: /mnt/nextcloud
    src: /dev/vdb
    fstype: ext4
    state: mounted

- name: Mount 
  ansible.posix.mount:
    path: /mnt/logs
    src: /dev/vdc
    fstype: ext4
    state: mounted

- name: Mount 
  ansible.posix.mount:
    path: /mnt/prometheus
    src: /dev/vdd
    fstype: ext4
    state: mounted


- name: Add NFS exports
  ansible.builtin.blockinfile:
    path: /etc/exports
    create: true
    block: |
      /mnt/nextcloud 10.129.0.0/24(rw,sync,no_subtree_check)
      /mnt/logs 10.129.0.0/24(rw,sync,no_subtree_check)
      /mnt/prometheus 10.129.0.0/24(rw,sync,no_subtree_check)


- name: Restart NFS
  ansible.builtin.systemd_service:
    name: nfs-kernel-server.service
    state: restarted
    enabled: true
