- name: Deploy SSH Public Key
  hosts: group
  become: true
  tasks:
    - name: Add SSH public key to authorized_keys
      ansible.posix.authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa_rebrain.pub') }}"